---
- hosts: all
  become: yes
  gather_facts: no
  vars_files:
  - vars/cluster_settings
  vars: ~

  tasks:
  - name: "Install {{ packages }}"
    yum:
        name: "{{ packages }}"
        state: latest
    vars:
      packages:
      - vim
      - git

  - name: Copy .vimrc
    template:
      src: vimrc.j2
      dest: /root/.vimrc

  - name: Copy .inputrc
    template:
      src: inputrc.j2
      dest: /root/.inputrc
