---
- hosts: all
  become: yes
  tasks:
  - name: Disabling Swap on all nodes
    command: swapoff -a

  - name: Commenting Swap entries in /etc/fstab
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'
    notify:
    - Reload systemd units

  - name: Create /etc/hosts
    template:
      src: hosts.j2
      dest: /etc/hosts

  handlers:
  - name: Reload systemd units
    systemd:
      daemon_reload: yes
