---
- hosts: all
  become: yes
  vars:
    selinux_policy: targeted
    selinux_state: permissive

  tasks:
  - name: Enable SELinux in permissive mode
    block:
    - include_role:
        name: rhel-system-roles.selinux
    rescue:
    # Fail if failed for a different reason than selinux_reboot_required
    - name: handle errors
      fail:
        msg: rhel-system-roles.selinux failed
      when: not selinux_reboot_required
    - name: restart the system
      reboot:
        msg: "rhel-system-roles: the update requires reboot"
    - name: reapply rhel-system-roles
      include_role:
        name: rhel-system-roles.selinux

  - name: Letting iptables see bridged traffic (1/2)
    copy:
      content: "br_netfilter"
      dest: /etc/modules-load.d/k8s.conf
    notify: Reload kernel parameters

  - name: Letting iptables see bridged traffic (2/2)
    copy:
      content: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
      dest: /etc/sysctl.d/k8s.conf
    notify: Reload kernel parameters

  - name: Remove obsoleted docker packages (installed from CentOS repo)
    yum:
      name: "{{ packages }}"
      state: removed
    vars:
      packages:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
  
  - name: Install prerequisite packages
    yum:
        name: "{{ packages }}"
        state: latest
    vars:
      packages:
      - yum-utils
      # device-mapper-persistent-data, lvm2 => no need in EL8
      - iproute-tc
      - bash-completion
  
  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo

  - name: Create /etc/docker
    file:
      path: /etc/docker
      state: directory

  # By default, docker uses cgroupfs as cgroup driver and kubelet  uses systemd 
  # https://github.com/kubernetes/kubeadm/issues/1394
  # https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/
  # https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker
  - name: Let the docker service use systemd cgroup driver
    copy:
      content: |
        {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "100m"
          },
          "storage-driver": "overlay2"
        }
      dest: /etc/docker/daemon.json
    notify:
      - Reload systemd units
      - Restart and enable services

  - name: Install docker
    yum:
      name: docker-ce
      state: latest
    notify: Restart and enable services

  - name: Adding repository details in Kubernetes repo file.
    copy:
      content: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        exclude=kubelet kubeadm kubectl
      dest: /etc/yum.repos.d/kubernetes.repo
  
  - name: Install kubernetes
    yum:
      name: "{{ packages }}"
      state: latest
      disable_excludes: kubernetes
      # workaround for update problem: https://github.com/kubernetes/kubernetes/issues/92463#issuecomment-685400015
      exclude:
        - kubelet-1.18.4-0
        - kubelet-1.17.7-0
        - kubelet-1.16.11-0
    vars:
      packages:
      - kubelet
      - kubeadm
      - kubectl
    notify: Restart and enable services
  
  handlers:
  - name: Reload kernel parameters
    command: sysctl --system

  - name: Reload systemd units
    systemd:
      daemon_reload: yes

  - name: Restart and enable services
    service:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    loop:
    - docker
    - kubelet
